minetest.register_tool("rangedweapons:bowcaster", {
	wield_scale = {x=1.9,y=1.9,z=2.5},
		description = "" ..core.colorize("#35cdff","Bowcaster\n") ..core.colorize("#FFFFFF", "Ranged damage: 16\n") ..core.colorize("#FFFFFF", "Accuracy: 85%\n") ..core.colorize("#FFFFFF", "Knockback: 3\n")  ..core.colorize("#FFFFFF", "Critical chance: 15%\n") ..core.colorize("#FFFFFF", "Critical efficiency: 2.0x\n") ..core.colorize("#FFFFFF", "Rate of fire: 0.5\n") ..core.colorize("#FFFFFF", "Enemy penetration: 40%"),
	range = 0,
    RW_powergun_capabilities = {
		automatic_gun = 1,
		power_damage = {fleshy=16,knockback=3},
		power_crit = 15,
		power_critEffc = 2.0,
		power_skill = {"",1},
		power_cooling = "rangedweapons:bowcaster",
		power_velocity = 60,
		power_accuracy = 85,
		power_cooldown = 0.5,
		power_projectiles = 1,
		power_durability = 12500,
		power_sound = "dh17",
		power_glass_breaking = 1,
		power_door_breaking = 1,
		power_dps = 0,
		power_mob_penetration = 40,
		power_node_penetration = 0,
		power_dps = 0,
		power_consumption = 0,
		power_entity = "rangedweapons:shot_bullet",
		power_visual = "wielditem",
		power_texture = "rangedweapons:blaster_bolt_red",
		power_projectile_size = 0.075,
		has_sparks = 0,
		ignites_explosives = 1,
	},
	inventory_image = "bowcaster.png",
})