minetest.register_tool("rangedweapons:dc15a", {
	wield_scale = {x=1.9,y=1.9,z=2.5},
		description = "" ..core.colorize("#35cdff","DC-15A blaster rifle\n") ..core.colorize("#FFFFFF", "Ranged damage: 18\n") ..core.colorize("#FFFFFF", "Accuracy: 90%\n") ..core.colorize("#FFFFFF", "Knockback: 0\n")  ..core.colorize("#FFFFFF", "Critical chance: 9%\n") ..core.colorize("#FFFFFF", "Critical efficiency: 2.0x\n") ..core.colorize("#FFFFFF", "Rate of fire: 0.5\n") ..core.colorize("#FFFFFF", "Enemy penetration: 40%"),
	range = 0,
    RW_powergun_capabilities = {
		automatic_gun = 1,
		power_damage = {fleshy=18,knockback=0},
		power_crit = 9,
		power_critEffc = 2.0,
		power_skill = {"",1},
		power_cooling = "rangedweapons:dc15a",
		power_velocity = 60,
		power_accuracy = 90,
		power_cooldown = 0.5,
		power_projectiles = 1,
		power_durability = 12500,
		power_sound = "dc15",
		power_glass_breaking = 1,
		power_door_breaking = 1,
		power_dps = 0,
		power_mob_penetration = 40,
		power_node_penetration = 0,
		power_dps = 0,
		power_consumption = 0,
		power_entity = "rangedweapons:shot_bullet",
		power_visual = "wielditem",
		power_texture = "rangedweapons:blaster_bolt_blue",
		power_projectile_size = 0.075,
		has_sparks = 0,
		ignites_explosives = 1,
	},
	inventory_image = "dc15a.png",
})