minetest.register_tool("rangedweapons:dlt19x", {
	wield_scale = {x=1.9,y=1.9,z=1.1},
		description = "" ..core.colorize("#35cdff","DLT-19x targeting blaster\n") ..core.colorize("#FFFFFF", "Ranged damage: 18 + 35/sec of bolt lifetime\n") ..core.colorize("#FFFFFF", "Accuracy: 100%\n") ..core.colorize("#FFFFFF", "Knockback: 15\n")  ..core.colorize("#FFFFFF", "Critical chance: 30%\n") ..core.colorize("#FFFFFF", "Critical efficiency: 3.0x\n") ..core.colorize("#FFFFFF", "Rate of fire: 2\n") ..core.colorize("#FFFFFF", "Enemy penetration: 30%\n") ..core.colorize("#FFFFFF", "Block penetration:10%"),
	range = 0,
    weapon_zoom = 7.5,
    RW_powergun_capabilities = {
		automatic_gun = 1,
		power_damage = {fleshy=18,knockback=15},
		power_crit = 30,
		power_critEffc = 3.0,
		power_skill = {"",1},
		power_cooling = "rangedweapons:dlt19x",
		power_velocity = 75,
		power_accuracy = 100,
		power_cooldown = 2,
		power_projectiles = 1,
		power_durability = 12500,
		power_sound = "e11",
		power_glass_breaking = 1,
		power_door_breaking = 1,
		power_dps = 35,
		power_mob_penetration = 30,
		power_node_penetration = 10,
		power_dps = 35,
		power_consumption = 0,
		power_entity = "rangedweapons:shot_bullet",
		power_visual = "wielditem",
		power_texture = "rangedweapons:blaster_bolt_red",
		power_projectile_size = 0.075,
		has_sparks = 0,
		ignites_explosives = 1,
	},
	inventory_image = "dlt19x.png",
})